# Generated by Django 5.2.2 on 2025-06-04 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_blogcategory_book_blogpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='will_read',
            field=models.BooleanField(default=False),
        ),
    ]
